# Generated by Django 5.1.3 on 2024-12-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_user_comment_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='post_images/', verbose_name='Зображення'),
        ),
    ]
