# Generated by Django 5.1.3 on 2024-12-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_comment_author_id_comment_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['updated_at']},
        ),
    ]
